# Generated by Django 4.2.7 on 2025-11-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transcripts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="videorecord",
            name="transcript",
            field=models.TextField(blank=True, null=True),
        ),
    ]
