# Generated by Django 4.2.7 on 2025-11-29 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transcripts", "0002_videorecord_transcript"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="videorecord",
            name="transcript",
        ),
    ]
